import type { ClinicalEvent, EndoCase } from "../types";
import { formatIsolationEventFragment, isolationEventTypes } from "../workflow/isolation";

export function eventFragment(event: ClinicalEvent) {
  if (Object.values(isolationEventTypes).includes(event.type as typeof isolationEventTypes[keyof typeof isolationEventTypes])) {
    return formatIsolationEventFragment(event);
  }

  const canal = event.canal ? `${event.canal}: ` : "";
  const snap = event.details?.canalSnapshot || {};
  const fragments: Record<string, string> = {
    "preop.reviewCompleted": "Pre-op review completed; chamber depth and estimated WL recorded where available.",
    "case.continuedFromPriorVisit": "Case continued from prior visit / outside system; prior treatment facts recorded as history.",
    "access.chamberReached": "Pulp chamber reached during access.",
    "access.markedDepthNoChamber": "Marked access depth reached without chamber entry; stopped for radiographic/clinical reassessment.",
    "access.radiographRedirected": "Radiograph taken and access direction reassessed/redirected.",
    "access.chamberConfirmed": "Chamber access confirmed with endodontic explorer.",
    "access.chamberNotConfirmed": "Chamber access could not be confirmed; reassessment pathway selected.",
    "access.refined": "Access outline refined.",
    "access.canalsIdentified": "Canals identified and recorded.",
    "scouting.estimatedWLSet": `${canal}10C stopper set to estimated WL ${snap.estimatedWorkingLength || "___"} mm.`,
    "scouting.estimatedWLReached": `${canal}10C reached estimated WL.`,
    "scouting.fileStoppedShort": `${canal}10C stopped short at ${snap.fileTerminalLength || "___"} mm.`,
    "scouting.availableSpaceGreaterThan16": `${canal}Available treatment space ${snap.availableTreatmentSpace || "___"} mm; proceeded with caution.`,
    "scouting.availableSpaceLimited": `${canal}Available treatment space limited to ${snap.availableTreatmentSpace || "___"} mm; increased difficulty noted.`,
    "difficulty.proceededWithExtremeCaution": "Treatment continued with extreme caution due to increased difficulty.",
    "difficulty.exceedsComfort": "Difficulty exceeded clinician comfort; stop/referral pathway selected.",
    "treatment.medicateTemporizeSelected": `${canal}Medication and temporization pathway selected.`,
    "treatment.referralSelected": `${canal}Referral pathway selected.`,
    "orifice.opened": `${canal}Canal orifice opened and irrigated.`,
    "canal.driedForEAL": `${canal}Canal dried before EAL measurement.`,
    "drying.persistentWetBeforeEAL": `${canal}Persistent wet canal noted before EAL measurement; medication pathway selected.`,
    "workingLength.ealPatencySignal": `${canal}EAL signaled patency.`,
    "workingLength.ealReadsShort": `${canal}EAL read short at terminal length; troubleshooting selected.`,
    "workingLength.established": `${canal}WL established: EAL0 ${snap.eal0 || "___"} mm, patency ${snap.patencyLength || "___"} mm, shaping ${snap.shapingLength || "___"} mm, reference ${snap.referencePoint || "___"}, WL PA ${snap.wlRadiographStatus || "___"}.`,
    "troubleshooting.fileResistance": `${canal}File resistance noted.`,
    "troubleshooting.fileStop": `${canal}File stop noted.`,
    "troubleshooting.prebendFileAdvanced": `${canal}Pre-bent 10C file advanced.`,
    "troubleshooting.prebendFailed": `${canal}Pre-bent 10C file did not advance; difficulty increased.`,
    "troubleshooting.middleThirdOpened": `${canal}Middle third opened with guide path file and irrigated.`,
    "troubleshooting.middleThirdNotSafe": `${canal}Could not safely advance in middle third; referral/stop pathway selected.`,
    "glidePath.patencyAchieved": `${canal}10C achieved patency length and became super loose.`,
    "glidePath.patencyShort": `${canal}10C stopped short of patency length.`,
    "glidePath.created": `${canal}Guide path created to EAL0 / guide path length.`,
    "glidePath.fileShort": `${canal}Guide path file did not reach EAL0.`,
    "shaping.gaugeNoResistance": `${canal}25 NiTi reached shaping length with no resistance; sequential gauge increase selected.`,
    "shaping.gaugeResistanceNearLength": `${canal}25 NiTi reached within 0 to 2 mm with resistance; proceeded to final shaping.`,
    "shaping.gaugeMoreThan2mmShort": `${canal}25 NiTi remained more than 2 mm short of shaping length.`,
    "shaping.nextGaugeReachedLength": `${canal}Next larger NiTi hand file reached shaping length; continued sequential gauging.`,
    "shaping.finalGaugeSelected": `${canal}Final shaping file selected as ${snap.finalShape || "___"}; next larger NiTi bound / did not reach shaping length.`,
    "shaping.gaugeIncreaseUnsafe": `${canal}Gauge increase not safe/predictable; returned to patency/glide path work.`,
    "shaping.finalShapeAchieved": `${canal}Final shaping completed with ${snap.finalShape || "___"}.`,
    "shaping.finalShapeShort": `${canal}Final shaping file did not reach shaping length.`,
    "shaping.completed": `${canal}Canal shaped, irrigated, and recapitulated.`,
    "drying.persistentWetAfterShaping": `${canal}Persistent wet canal noted after shaping; completion deferred.`,
    "smearLayer.edtaPlaced": `${canal}17% EDTA placed for 90 to 120 seconds for smear layer removal.`,
    "smearLayer.edtaAgitated": `${canal}EDTA agitated with measured GP cone without exceeding shaping length.`,
    "smearLayer.deferred": `${canal}Smear layer removal deferred; medication/temporization pathway selected.`,
    "smearLayer.agitationDeferred": `${canal}EDTA agitation was not predictable; medication/temporization pathway selected.`,
    "disinfection.finalNaOClCompleted": `${canal}Final NaOCl disinfection completed.`,
    "disinfection.cannotCompleteToday": `${canal}Final disinfection/obturation could not be completed today.`,
    "disinfection.readyForObturation": `${canal}Canal ready for obturation gauging.`,
    "obturationGauge.size30Stop": `${canal}Size 30 NiTi hand file reached shaping length and did not advance beyond under firm pressure.`,
    "obturationGauge.size30AdvancesBeyond": `${canal}Size 30 NiTi hand file advanced beyond shaping length under firm pressure; larger gauge selected.`,
    "obturationGauge.size30Short": `${canal}Size 30 NiTi hand file did not reach shaping length; size 25 gauge selected.`,
    "obturationGauge.size25Stop": `${canal}Size 25 NiTi hand file reached shaping length and did not advance beyond under firm pressure.`,
    "obturationGauge.size25AdvancesBeyond": `${canal}Size 25 NiTi hand file advanced beyond shaping length under firm pressure; larger gauge selected.`,
    "obturationGauge.size25Short": `${canal}Size 25 NiTi hand file did not reach shaping length; returned to patency/shaping pathway.`,
    "obturationGauge.largerSizeStop": `${canal}Larger NiTi hand file reached shaping length and did not advance beyond under firm pressure.`,
    "obturationGauge.largerSizeAdvancesBeyond": `${canal}Larger NiTi hand file continued to advance beyond shaping length; continued sequential gauging.`,
    "obturationGauge.recorded": `${canal}Obturation gauge recorded as ${snap.obturationGauge || "___"}.`,
    "coneFit.masterConeFits": `${canal}Master cone selected as ${snap.masterCone || "___"} and fit to shaping length.`,
    "coneFit.masterConeShort": `${canal}Master cone was short of shaping length; short-cone troubleshooting selected.`,
    "coneFit.masterConeLong": `${canal}Master cone advanced beyond shaping length; long-cone troubleshooting selected.`,
    "coneFit.smallerConeFits": `${canal}One-size-smaller master cone fit to shaping length.`,
    "coneFit.smallerConeStillShort": `${canal}One-size-smaller master cone remained short; returned to final shaping pathway.`,
    "coneFit.smallerConeLong": `${canal}One-size-smaller master cone advanced beyond shaping length; long-cone troubleshooting selected.`,
    "coneFit.trimmedConeFits": `${canal}Long master cone was crimped, measured, trimmed, and fit to shaping length.`,
    "coneFit.trimmedConeStillNotFit": `${canal}Trimmed master cone still did not fit; short-cone troubleshooting selected.`,
    "coneFit.coneStillLong": `${canal}Master cone remained long after trimming; repeated long-cone troubleshooting.`,
    "coneFit.radiographAcceptable": `${canal}Cone fit radiograph acceptable.`,
    "coneFit.radiographShort": `${canal}Cone fit radiograph showed short cone position; short-cone troubleshooting selected.`,
    "coneFit.radiographLong": `${canal}Cone fit radiograph showed long cone position; long-cone troubleshooting selected.`,
    "coneFit.readyForSealerConeSeating": `${canal}Cone fit complete; ready for sealer and cone seating workflow.`,
    "drying.readyForSealer": `${canal}Canal dried to dry/slightly damp paper point at shaping length; ready for sealer.`,
    "drying.paperPointWet": `${canal}Paper point remained wet; drying repeated.`,
    "drying.persistentWetBeforeObturation": `${canal}Persistent wet canal noted before obturation; medication pathway selected.`,
    "sealer.patencyConfirmed": `${canal}10C file confirmed super loose patency before sealer placement.`,
    "sealer.patencyNotConfirmed": `${canal}Patency could not be confirmed before sealer placement; troubleshooting selected.`,
    "sealer.applied": `${canal}Bioceramic sealer applied with passive White NaviTip withdrawal.`,
    "sealer.naviTipUnsafe": `${canal}White NaviTip placement was not safe/predictable; medication pathway selected.`,
    "sealer.paperPointDistributed": `${canal}Paper point passed through sealer to shaping length to distribute sealer.`,
    "sealer.paperPointShort": `${canal}Paper point did not reach shaping length after sealer placement; returned to patency confirmation.`,
    "sealer.reapplied": `${canal}Bioceramic sealer re-applied.`,
    "sealer.reapplyUnsafe": `${canal}Sealer re-application was not safe/predictable; medication pathway selected.`,
    "gpSeating.coneSeated": `${canal}Pre-fit GP cone seated to shaping length.`,
    "gpSeating.coneShortAfterSealer": `${canal}GP cone did not seat to shaping length after sealer placement; returned to patency confirmation.`,
    "gpSeating.coneLongAfterSealer": `${canal}GP cone advanced beyond shaping length after sealer placement; returned to obturation gauging.`,
    "downpack.noGapSpace": `${canal}No visible orifice gap after GP cone seating; proceeded to sear GP.`,
    "downpack.roundGapSpace": `${canal}Round visible orifice gap after GP seating; accessory cone pathway selected.`,
    "downpack.ovoidGapSpace": `${canal}Ovoid visible orifice gap after GP seating; modified downpack selected.`,
    "downpack.modifiedSuccessful": `${canal}Modified downpack removed coronal GP while apical GP remained stable.`,
    "downpack.littleGpRemoved": `${canal}Modified downpack removed little or no GP; repeated modified downpack.`,
    "downpack.coneMoved": `${canal}GP cone moved during downpack; returned to master cone fitting.`,
    "downpack.accessoryConesAdded": `${canal}Accessory GP cones added until no visible gap remained.`,
    "downpack.accessoryConeDifficulty": `${canal}Accessory cone placement was not predictable; modified downpack selected.`,
    "downpack.gpSeared": `${canal}GP cone(s) seared at the orifice.`,
    "downpack.gpStableAfterCompaction": `${canal}GP maintained position after vertical compaction.`,
    "downpack.gpMovedApically": `${canal}GP moved apically during compaction; sealer over visible GP selected before backfill.`,
    "backfill.sealerOnGp": `${canal}Sealer applied over visible GP before backfill.`,
    "backfill.completed": `${canal}Thermoplastic GP backfill completed.`,
    "backfill.difficulty": `${canal}Backfill was not predictable; sealer over visible GP repeated before retry.`,
    "backfill.compactedStable": `${canal}Backfilled GP compacted and remained stable at the canal orifice.`,
    "backfill.gpMovedApically": `${canal}Backfilled GP moved apically during compaction; sealer over visible GP selected before retry.`,
    "backfill.excessInChamber": `${canal}Excess GP extended into the chamber after backfill.`,
    "backfill.pluggerHoles": `${canal}Plugger created holes during compaction; backfill repeated as needed.`,
    "closure.chamberGpRemoved": "Excess GP and residual sealer removed from chamber.",
    "closure.chamberRinsed": "Pulp chamber rinsed until residual sealer was removed.",
    "closure.temporary": "Access closed with sponge and temporary restorative material.",
    "closure.orificeBarrierTemporary": "Orifice barrier and temporary restoration placed.",
    "closure.finalRestoration": "Final restoration placed.",
    "drying.canalDriedAfterRepeat": `${canal}Canal dried after repeat drying attempts.`,
    "drying.persistentWetConfirmed": `${canal}Persistent wet canal confirmed after repeat drying attempts.`,
    "medication.calciumHydroxidePlaced": `${canal}Calcium hydroxide placed.`,
    "canal.completed": `${canal}Marked complete by clinician.`,
    "canal.paused": `${canal}Paused for later continuation.`,
    "canal.medicated": `${canal}Marked medicated/staged for continuation.`,
    "canal.referred": `${canal}Marked for referral or specialist continuation.`,
    "workflow.startedNextCanal": "Workflow moved to next canal.",
    "workflow.nextCanalSelected": "Workflow continued to another canal.",
    "workflow.nextCanalBeforeClosure": "Workflow continued to another canal before final chamber cleanup/closure.",
    "workflow.switchedCanal": `Workflow switched from ${event.details?.previousCanal || event.details?.previousActiveCanal || "previous canal"} to ${event.details?.nextCanal || event.details?.newActiveCanal || event.canal || "selected canal"}; ${event.details?.phaseLabel ? `continued at ${event.details.phaseLabel}` : event.details?.reason || "continued selected canal"}.`,
    "workflow.resumedFromPriorVisit": `Workflow resumed ${event.canal || "selected canal"} from prior visit history at ${event.details?.phaseLabel || event.details?.nextNodeId || "confirmed resume point"}.`,
    "workflow.allCanalsReadyForClosure": "All canals ready for chamber cleanup and closure.",
    "treatment.referralRecommended": `${canal}Referral or specialist continuation recommended.`,
    "treatment.referralOnlyCompleted": `${canal}Referral note completed without medication/temporization at this visit.`,
    "workflow.returnedToStart": "Workflow returned to start.",
  };
  return fragments[event.type] || `${canal}${event.type}.`;
}

export function groupEventsByPrefix(caseData: EndoCase, prefixes: string[]) {
  return (caseData.globalEvents || [])
    .filter((event) => prefixes.some((prefix) => event.type.startsWith(prefix)))
    .map(eventFragment);
}

export function appendSection(lines: string[], title: string, items: string[]) {
  lines.push(title);
  if (!items.length) lines.push("- Not recorded.");
  else items.forEach((item) => lines.push(`- ${item}`));
  lines.push("");
}
