import type { ProtocolNode } from "../types";

export const protocolNodes: Record<string, ProtocolNode> = {
  preop: {
    id: "preop",
    phase: "Pre-op",
    title: "Pre-op setup",
    chairsideInstruction: "Review pre-op radiographs and record chamber depth plus estimated WL for the active canal.",
    instruments: ["Pre-op PA/BW", "CBCT if available", "Rubber dam armamentarium"],
    requiredInputs: ["Tooth", "Procedure", "Chamber depth", "Estimated WL"],
    safetyNotes: ["Workflow/documentation aid only. Clinical judgment and referral thresholds still apply."],
    options: [{ label: "Pre-op review complete", nextNodeId: "access-chamber", noteEvent: { type: "preop.reviewCompleted" } }],
  },
  "access-chamber": {
    id: "access-chamber",
    phase: "Access",
    title: "Access pulp chamber",
    chairsideInstruction: "Mark 557 bur to the target vertical depth. Access toward the pulp chamber and rinse as needed.",
    instruments: ["557 bur", "Water rinse"],
    requiredInputs: ["Chamber depth"],
    safetyNotes: ["If marked depth is reached and chamber is not found, stop and reassess radiographically."],
    options: [
      { label: "Chamber reached", nextNodeId: "confirm-chamber", noteEvent: { type: "access.chamberReached" } },
      { label: "Marked depth reached but chamber not found", nextNodeId: "access-reassess", difficultyFlag: "caution", noteEvent: { type: "access.markedDepthNoChamber" } },
    ],
  },
  "access-reassess": {
    id: "access-reassess",
    phase: "Access",
    title: "Stop and reassess access direction",
    chairsideInstruction: "Capture BW/PA as appropriate, reassess orientation, and redirect only after radiographic/clinical review.",
    instruments: ["BW/PA radiograph", "DG16/17", "557 bur"],
    safetyNotes: ["Do not continue blindly beyond the marked depth."],
    options: [
      { label: "Radiograph taken and access redirected", nextNodeId: "access-chamber", noteEvent: { type: "access.radiographRedirected" } },
      { label: "Difficulty exceeds comfort", nextNodeId: "refer-pathway", difficultyFlag: "refer", noteEvent: { type: "difficulty.exceedsComfort" } },
    ],
  },
  "confirm-chamber": {
    id: "confirm-chamber",
    phase: "Access",
    title: "Confirm chamber access",
    chairsideInstruction: "Confirm chamber entry with a DG16/17 endodontic explorer.",
    instruments: ["DG16/17 Endo Explorer"],
    options: [
      { label: "Pulp chamber confirmed", nextNodeId: "refine-access", noteEvent: { type: "access.chamberConfirmed" } },
      { label: "Chamber not confirmed", nextNodeId: "access-reassess", difficultyFlag: "caution", noteEvent: { type: "access.chamberNotConfirmed" } },
    ],
  },
  "refine-access": {
    id: "refine-access",
    phase: "Access",
    title: "Refine access outline",
    chairsideInstruction: "Refine access outline with Endo-Z bur and rinse as needed.",
    instruments: ["Endo-Z bur", "Water rinse"],
    options: [{ label: "Access refined", nextNodeId: "identify-canals", noteEvent: { type: "access.refined" } }],
  },
  "identify-canals": {
    id: "identify-canals",
    phase: "Access",
    title: "Identify canals",
    chairsideInstruction: "Identify canals with DG16/17 explorer. Add or rename canals in the canal panel.",
    instruments: ["DG16/17 Endo Explorer"],
    requiredInputs: ["At least one canal name"],
    options: [{ label: "Canals identified", nextNodeId: "estimate-wl", noteEvent: { type: "access.canalsIdentified" } }],
  },
  "estimate-wl": {
    id: "estimate-wl",
    phase: "Initial scouting",
    title: "Estimate working length",
    chairsideInstruction: "Estimate WL from pre-op PA and set the 10C file stopper for the active canal.",
    instruments: ["Pre-op PA", "10C hand file"],
    requiredInputs: ["Estimated WL for active canal"],
    options: [{ label: "10C stopper set to estimated WL", nextNodeId: "advance-10c", noteEvent: { type: "scouting.estimatedWLSet" } }],
  },
  "advance-10c": {
    id: "advance-10c",
    phase: "Initial scouting",
    title: "Advance 10C to passive resistance",
    chairsideInstruction: "Place lubricant or aqueous irrigation. Advance 10C to passive resistance without exceeding estimated WL.",
    instruments: ["10C hand file"],
    materials: ["File lubricant or aqueous irrigation"],
    requiredInputs: ["Estimated WL", "10C terminal length if short"],
    safetyNotes: ["Do not exceed estimated WL."],
    options: [
      {
        label: "10C reached estimated WL",
        nextNodeId: "open-orifice",
        noteEvent: { type: "scouting.estimatedWLReached" },
        guards: [
          { type: "required", scope: "activeCanal", field: "estimatedWorkingLength", message: "Estimated WL for active canal" },
          { type: "custom", id: "tenCReachedEstimatedWL", message: "10C terminal length is shorter than estimated WL, so this option cannot be selected" },
        ],
      },
      {
        label: "10C stopped short",
        nextNodeId: "measure-available-space",
        noteEvent: { type: "scouting.fileStoppedShort" },
        guards: [
          { type: "required", scope: "activeCanal", field: "estimatedWorkingLength", message: "Estimated WL for active canal" },
          { type: "required", scope: "activeCanal", field: "fileTerminalLength", message: "10C terminal length" },
          { type: "custom", id: "tenCStoppedShort", message: "10C terminal length is not shorter than estimated WL, so this option cannot be selected" },
        ],
      },
    ],
  },
  "measure-available-space": {
    id: "measure-available-space",
    phase: "Initial scouting",
    title: "Measure available treatment space",
    chairsideInstruction: "With 10C at terminal position, adjust stopper to a reproducible reference point, remove, and measure available treatment space.",
    instruments: ["10C hand file", "Endo ruler"],
    requiredInputs: ["Available treatment space", "Reference point"],
    options: [
      {
        label: "Available treatment space >16 mm",
        nextNodeId: "open-orifice",
        difficultyFlag: "caution",
        noteEvent: { type: "scouting.availableSpaceGreaterThan16" },
        guards: [
          { type: "required", scope: "activeCanal", field: "availableTreatmentSpace", message: "Available treatment space in mm" },
          { type: "required", scope: "activeCanal", field: "referencePoint", message: "Reference point" },
          { type: "numericComparison", scope: "activeCanal", field: "availableTreatmentSpace", operator: ">", value: 16, message: "Available treatment space must be >16 mm for this option" },
        ],
      },
      {
        label: "Available treatment space ≤16 mm",
        nextNodeId: "limited-space-warning",
        difficultyFlag: "high",
        noteEvent: { type: "scouting.availableSpaceLimited" },
        guards: [
          { type: "required", scope: "activeCanal", field: "availableTreatmentSpace", message: "Available treatment space in mm" },
          { type: "required", scope: "activeCanal", field: "referencePoint", message: "Reference point" },
          { type: "numericComparison", scope: "activeCanal", field: "availableTreatmentSpace", operator: "<=", value: 16, message: "Available treatment space must be ≤16 mm for this option" },
        ],
      },
    ],
  },
  "limited-space-warning": {
    id: "limited-space-warning",
    phase: "Troubleshooting",
    title: "Limited treatment space warning",
    chairsideInstruction: "Available treatment space is ≤16 mm. Case difficulty increases significantly.",
    safetyNotes: ["Consider staged care, CBCT review, magnification, or referral."],
    options: [
      { label: "Proceed with extreme caution", nextNodeId: "open-orifice", difficultyFlag: "high", noteEvent: { type: "difficulty.proceededWithExtremeCaution" } },
      { label: "Medicate and temporize", nextNodeId: "calcium-hydroxide", difficultyFlag: "refer", noteEvent: { type: "treatment.medicateTemporizeSelected" } },
      { label: "Refer", nextNodeId: "refer-pathway", difficultyFlag: "refer", noteEvent: { type: "treatment.referralSelected" } },
    ],
  },
  "open-orifice": {
    id: "open-orifice",
    phase: "Working length",
    title: "Open canal orifice",
    chairsideInstruction: "Open canal orifice with an orifice opener. Do not exceed 15 mm. Irrigate with diluted NaOCl.",
    instruments: ["Orifice opener file"],
    materials: ["Diluted NaOCl"],
    safetyNotes: ["Do not exceed 15 mm with the orifice opener."],
    options: [{ label: "Orifice opened and irrigated", nextNodeId: "dry-canal", noteEvent: { type: "orifice.opened" } }],
  },
  "dry-canal": {
    id: "dry-canal",
    phase: "Working length",
    title: "Dry canal for EAL",
    chairsideInstruction: "Dry canal with measured paper points before electronic working length.",
    instruments: ["25/.04 paper points"],
    options: [
      { label: "Canal dried", nextNodeId: "attach-eal", noteEvent: { type: "canal.driedForEAL" } },
      { label: "Canal remains wet", nextNodeId: "persistent-wet", difficultyFlag: "high", noteEvent: { type: "drying.persistentWetBeforeEAL" } },
    ],
  },
  "attach-eal": {
    id: "attach-eal",
    phase: "Working length",
    title: "Attach EAL to 10C file",
    chairsideInstruction: "Attach EAL to 10C hand file and attempt to establish electronic WL.",
    instruments: ["EAL", "10C hand file"],
    options: [
      { label: "EAL signals patency", nextNodeId: "establish-eal0", noteEvent: { type: "workingLength.ealPatencySignal" } },
      { label: "EAL reads short at terminal length", nextNodeId: "file-stop-vs-resistance", difficultyFlag: "caution", noteEvent: { type: "workingLength.ealReadsShort" } },
    ],
  },
  "file-stop-vs-resistance": {
    id: "file-stop-vs-resistance",
    phase: "Troubleshooting",
    title: "File resistance vs file stop",
    chairsideInstruction: "Determine whether the 10C is encountering file resistance or a file stop.",
    options: [
      { label: "File resistance", nextNodeId: "middle-third-guide-path", difficultyFlag: "caution", noteEvent: { type: "troubleshooting.fileResistance" } },
      { label: "File stop", nextNodeId: "prebend-10c", difficultyFlag: "high", noteEvent: { type: "troubleshooting.fileStop" } },
      { label: "Difficulty exceeds comfort", nextNodeId: "refer-pathway", difficultyFlag: "refer", noteEvent: { type: "difficulty.exceedsComfort" } },
    ],
  },
  "prebend-10c": {
    id: "prebend-10c",
    phase: "Troubleshooting",
    title: "Pre-bend 10C file",
    chairsideInstruction: "Place lubricant or aqueous irrigation. Use file bending technique with 10C and reassess advancement.",
    instruments: ["10C hand file"],
    materials: ["File lubricant or aqueous irrigation"],
    options: [
      { label: "File advances", nextNodeId: "dry-canal", noteEvent: { type: "troubleshooting.prebendFileAdvanced" } },
      { label: "File does not advance", nextNodeId: "limited-space-warning", difficultyFlag: "high", noteEvent: { type: "troubleshooting.prebendFailed" } },
    ],
  },
  "middle-third-guide-path": {
    id: "middle-third-guide-path",
    phase: "Troubleshooting",
    title: "Open middle third",
    chairsideInstruction: "Open middle third with guide path file to resistance. Do not exceed available treatment space.",
    instruments: ["Guide path file"],
    materials: ["File lubricant or aqueous irrigation", "Diluted NaOCl"],
    safetyNotes: ["Do not exceed available treatment space."],
    options: [
      { label: "Middle third opened and irrigated", nextNodeId: "dry-canal", noteEvent: { type: "troubleshooting.middleThirdOpened" } },
      { label: "Cannot safely advance", nextNodeId: "refer-pathway", difficultyFlag: "refer", noteEvent: { type: "troubleshooting.middleThirdNotSafe" } },
    ],
  },
  "establish-eal0": {
    id: "establish-eal0",
    phase: "Working length",
    title: "Establish EAL 0",
    chairsideInstruction: "Adjust 10C until EAL reads 0. Capture WL radiograph and record EAL 0, patency length, shaping length, and reference point.",
    instruments: ["EAL", "10C hand file", "WL radiograph"],
    requiredInputs: ["EAL 0", "Patency length", "Shaping length", "Reference point"],
    options: [
      {
        label: "EAL 0 recorded and WL radiograph taken",
        nextNodeId: "patency-10c",
        noteEvent: { type: "workingLength.established" },
        guards: [
          { type: "required", scope: "activeCanal", field: "eal0", message: "EAL 0 in mm" },
          { type: "required", scope: "activeCanal", field: "patencyLength", message: "Patency length in mm" },
          { type: "required", scope: "activeCanal", field: "shapingLength", message: "Shaping length in mm" },
          { type: "required", scope: "activeCanal", field: "referencePoint", message: "Reference point" },
          { type: "required", scope: "activeCanal", field: "wlRadiographStatus", message: "WL PA status" },
        ],
      },
    ],
  },
  "patency-10c": {
    id: "patency-10c",
    phase: "Glide path",
    title: "10C to patency length until super loose",
    chairsideInstruction: "Measure 10C to patency length. Work in filing/reciprocating motion until super loose. Irrigate.",
    instruments: ["10C hand file"],
    materials: ["Diluted NaOCl", "File lubricant or aqueous irrigation"],
    requiredInputs: ["Patency length"],
    options: [
      { label: "10C achieved patency length and is super loose", nextNodeId: "guide-path", noteEvent: { type: "glidePath.patencyAchieved" } },
      { label: "10C stops short of patency length", nextNodeId: "prebend-10c", difficultyFlag: "high", noteEvent: { type: "glidePath.patencyShort" } },
    ],
  },
  "guide-path": {
    id: "guide-path",
    phase: "Glide path",
    title: "Create guide path",
    chairsideInstruction: "Measure guide path file to EAL 0 and advance. Irrigate after use.",
    instruments: ["Guide path file"],
    materials: ["Diluted NaOCl"],
    requiredInputs: ["EAL 0 / guide path length"],
    options: [
      { label: "Guide path file reached EAL 0", nextNodeId: "gauge-final-shape", noteEvent: { type: "glidePath.created" } },
      { label: "Guide path file did not reach EAL 0", nextNodeId: "patency-10c", difficultyFlag: "caution", noteEvent: { type: "glidePath.fileShort" } },
    ],
  },
  "gauge-final-shape": {
    id: "gauge-final-shape",
    phase: "Shaping",
    title: "Gauge for final shape",
    chairsideInstruction: "Set 25 NiTi hand file to shaping length. Advance and assess resistance. If it reaches length with no resistance, sequentially gauge larger NiTi hand files before selecting the final shaping file/system. If it reaches within 0 to 2 mm with resistance, proceed to final shaping.",
    instruments: ["25 NiTi hand file", "Sequentially larger NiTi hand files"],
    requiredInputs: ["Shaping length"],
    options: [
      { label: "25 NiTi reaches shaping length with no resistance", nextNodeId: "increase-shaping-gauge", noteEvent: { type: "shaping.gaugeNoResistance" } },
      { label: "25 NiTi reaches within 0 to 2 mm with resistance", nextNodeId: "create-final-shape", difficultyFlag: "caution", noteEvent: { type: "shaping.gaugeResistanceNearLength" } },
      { label: "25 NiTi more than 2 mm short", nextNodeId: "patency-10c", difficultyFlag: "high", noteEvent: { type: "shaping.gaugeMoreThan2mmShort" } },
    ],
  },
  "increase-shaping-gauge": {
    id: "increase-shaping-gauge",
    phase: "Shaping",
    title: "Increase NiTi hand-file gauge",
    chairsideInstruction: "Use the next size NiTi hand file at shaping length. Continue increasing one ISO size at a time until the next larger file no longer reaches shaping length or has clear binding/resistance. Record the largest size that predictably reaches shaping length, then choose the final shaping file/system.",
    instruments: ["Sequential NiTi hand files"],
    requiredInputs: ["Shaping length", "Final shaping file"],
    options: [
      { label: "Next larger NiTi reaches shaping length; continue gauging", nextNodeId: "increase-shaping-gauge", noteEvent: { type: "shaping.nextGaugeReachedLength" } },
      { label: "Next larger NiTi binds / does not reach shaping length", nextNodeId: "create-final-shape", noteEvent: { type: "shaping.finalGaugeSelected" } },
      { label: "Cannot safely increase gauge", nextNodeId: "patency-10c", difficultyFlag: "high", noteEvent: { type: "shaping.gaugeIncreaseUnsafe" } },
    ],
  },
  "create-final-shape": {
    id: "create-final-shape",
    phase: "Shaping",
    title: "Complete final shaping",
    chairsideInstruction: "Select the final shaping file according to the canal anatomy, glide path, gauging result, and file system being used. Shape to the recorded shaping length. Record the final shaping file/system.",
    instruments: ["Final shaping file/system"],
    requiredInputs: ["Final shaping file"],
    options: [
      {
        label: "Final shaping file reached shaping length",
        nextNodeId: "irrigate-recapitulate",
        noteEvent: { type: "shaping.finalShapeAchieved" },
        guards: [{ type: "custom", id: "validFinalShape", message: "Final shaping file, e.g. 30/.04 or PTN X2 25/.06" }],
      },
      { label: "Final shaping file did not reach shaping length", nextNodeId: "patency-10c", difficultyFlag: "caution", noteEvent: { type: "shaping.finalShapeShort" } },
    ],
  },
  "irrigate-recapitulate": {
    id: "irrigate-recapitulate",
    phase: "Shaping",
    title: "Irrigate and recapitulate",
    chairsideInstruction: "Irrigate with NaOCl. Recapitulate with 10C to patency length until super loose.",
    instruments: ["10C hand file", "Irrigation syringe"],
    materials: ["NaOCl"],
    options: [
      { label: "Canal shaped and recapitulated", nextNodeId: "remove-smear-layer", noteEvent: { type: "shaping.completed" } },
      { label: "Canal remains wet / cannot complete today", nextNodeId: "persistent-wet", difficultyFlag: "high", noteEvent: { type: "drying.persistentWetAfterShaping" } },
      { label: "Medicate and temporize", nextNodeId: "calcium-hydroxide", noteEvent: { type: "treatment.medicateTemporizeSelected" } },
    ],
  },
  "remove-smear-layer": {
    id: "remove-smear-layer",
    phase: "Smear / disinfection",
    title: "Remove smear layer",
    chairsideInstruction: "Irrigate with 17% EDTA. Ideal canal exposure to EDTA is 90 to 120 seconds.",
    materials: ["17% EDTA"],
    requiredInputs: ["Shaping length", "Final shaping file"],
    safetyNotes: ["Do not proceed to final disinfection until shaping is complete and canal length data are recorded."],
    options: [
      { label: "17% EDTA placed for 90 to 120 seconds", nextNodeId: "agitate-edta", noteEvent: { type: "smearLayer.edtaPlaced" } },
      { label: "Canal cannot be completed today", nextNodeId: "calcium-hydroxide", difficultyFlag: "high", noteEvent: { type: "smearLayer.deferred" } },
    ],
  },
  "agitate-edta": {
    id: "agitate-edta",
    phase: "Smear / disinfection",
    title: "Agitate EDTA",
    chairsideInstruction: "Agitate EDTA with a measured 30/.04 GP cone at shaping length using a 2 to 3 mm pumping motion. Do not exceed shaping length.",
    instruments: ["30/.04 GP cone"],
    materials: ["17% EDTA"],
    requiredInputs: ["Shaping length"],
    safetyNotes: ["Do not exceed shaping length during agitation."],
    options: [
      { label: "EDTA agitated without exceeding shaping length", nextNodeId: "final-naocl", noteEvent: { type: "smearLayer.edtaAgitated" } },
      { label: "Unable to agitate predictably", nextNodeId: "calcium-hydroxide", difficultyFlag: "high", noteEvent: { type: "smearLayer.agitationDeferred" } },
    ],
  },
  "final-naocl": {
    id: "final-naocl",
    phase: "Smear / disinfection",
    title: "Final NaOCl disinfection",
    chairsideInstruction: "Irrigate with concentrated NaOCl and leave it in the canal for final disinfection before obturation gauging.",
    materials: ["Concentrated NaOCl"],
    options: [
      { label: "Final NaOCl disinfection completed", nextNodeId: "ready-for-obturation", noteEvent: { type: "disinfection.finalNaOClCompleted" } },
      { label: "Canal remains wet / cannot complete today", nextNodeId: "persistent-wet", difficultyFlag: "high", noteEvent: { type: "disinfection.cannotCompleteToday" } },
    ],
  },
  "ready-for-obturation": {
    id: "ready-for-obturation",
    phase: "Smear / disinfection",
    title: "Ready for obturation gauging",
    chairsideInstruction: "Smear layer removal and final disinfection are complete. Proceed to obturation gauging.",
    options: [
      { label: "Proceed to obturation gauging", nextNodeId: "gauge-obturation-30", noteEvent: { type: "disinfection.readyForObturation" } },
    ],
  },
  "gauge-obturation-30": {
    id: "gauge-obturation-30",
    phase: "Obturation gauging",
    title: "Gauge obturation with size 30 NiTi",
    chairsideInstruction: "Set size 30 NiTi hand file to shaping length. Advance to shaping length and apply firm apical pressure.",
    instruments: ["Size 30 NiTi hand file"],
    requiredInputs: ["Shaping length"],
    options: [
      { label: "Size 30 reaches shaping length and does not advance beyond", nextNodeId: "record-obturation-gauge", noteEvent: { type: "obturationGauge.size30Stop" } },
      { label: "Size 30 reaches shaping length and advances beyond", nextNodeId: "gauge-obturation-larger", difficultyFlag: "caution", noteEvent: { type: "obturationGauge.size30AdvancesBeyond" } },
      { label: "Size 30 does not reach shaping length", nextNodeId: "gauge-obturation-25", difficultyFlag: "caution", noteEvent: { type: "obturationGauge.size30Short" } },
    ],
  },
  "gauge-obturation-25": {
    id: "gauge-obturation-25",
    phase: "Obturation gauging",
    title: "Gauge obturation with size 25 NiTi",
    chairsideInstruction: "Set size 25 NiTi hand file to shaping length. Advance to shaping length and apply firm apical pressure.",
    instruments: ["Size 25 NiTi hand file"],
    requiredInputs: ["Shaping length"],
    options: [
      { label: "Size 25 reaches shaping length and does not advance beyond", nextNodeId: "record-obturation-gauge", noteEvent: { type: "obturationGauge.size25Stop" } },
      { label: "Size 25 reaches shaping length and advances beyond", nextNodeId: "gauge-obturation-larger", difficultyFlag: "caution", noteEvent: { type: "obturationGauge.size25AdvancesBeyond" } },
      { label: "Size 25 does not reach shaping length", nextNodeId: "patency-10c", difficultyFlag: "high", noteEvent: { type: "obturationGauge.size25Short" } },
    ],
  },
  "gauge-obturation-larger": {
    id: "gauge-obturation-larger",
    phase: "Obturation gauging",
    title: "Gauge with next larger NiTi file",
    chairsideInstruction: "Set the next successively larger NiTi hand file to shaping length. Advance and apply firm apical pressure until a size reaches shaping length and does not advance beyond.",
    instruments: ["NiTi hand files"],
    requiredInputs: ["Obturation gauge size"],
    options: [
      { label: "Larger NiTi size stops at shaping length", nextNodeId: "record-obturation-gauge", noteEvent: { type: "obturationGauge.largerSizeStop" } },
      { label: "Larger NiTi continues to advance beyond", nextNodeId: "gauge-obturation-larger", difficultyFlag: "caution", noteEvent: { type: "obturationGauge.largerSizeAdvancesBeyond" } },
    ],
  },
  "record-obturation-gauge": {
    id: "record-obturation-gauge",
    phase: "Obturation gauging",
    title: "Record obturation gauge",
    chairsideInstruction: "Record the NiTi hand file size that achieved shaping length and did not advance beyond under firm apical pressure.",
    requiredInputs: ["Obturation gauge size"],
    options: [{ label: "Obturation gauge recorded", nextNodeId: "fit-master-cone", noteEvent: { type: "obturationGauge.recorded" } }],
  },
  "fit-master-cone": {
    id: "fit-master-cone",
    phase: "Cone fit",
    title: "Fit .04 tapered master cone",
    chairsideInstruction: "Choose a .04 tapered GP cone matching the recorded obturation gauge size. Measure to shaping length and place to shaping length.",
    instruments: [".04 tapered GP cone"],
    requiredInputs: ["Master cone", "Shaping length"],
    options: [
      { label: "Master cone fits to shaping length", nextNodeId: "cone-fit-radiograph", noteEvent: { type: "coneFit.masterConeFits" } },
      { label: "Master cone is short", nextNodeId: "cone-short", difficultyFlag: "caution", noteEvent: { type: "coneFit.masterConeShort" } },
      { label: "Master cone is long", nextNodeId: "cone-long", difficultyFlag: "caution", noteEvent: { type: "coneFit.masterConeLong" } },
    ],
  },
  "cone-short": {
    id: "cone-short",
    phase: "Cone fit",
    title: "Master cone short",
    chairsideInstruction: "Try a .04 tapered GP cone one size smaller. If the smaller cone still does not reach shaping length, return to final shaping.",
    instruments: ["One-size-smaller .04 GP cone"],
    options: [
      { label: "Smaller cone fits to shaping length", nextNodeId: "cone-fit-radiograph", noteEvent: { type: "coneFit.smallerConeFits" } },
      { label: "Smaller cone still short", nextNodeId: "create-final-shape", difficultyFlag: "high", noteEvent: { type: "coneFit.smallerConeStillShort" } },
      { label: "Smaller cone is long", nextNodeId: "cone-long", difficultyFlag: "caution", noteEvent: { type: "coneFit.smallerConeLong" } },
    ],
  },
  "cone-long": {
    id: "cone-long",
    phase: "Cone fit",
    title: "Master cone long",
    chairsideInstruction: "Crimp the engaged cone at the reference point, remove and measure it, subtract shaping length, trim excess, and retry cone fit.",
    instruments: ["Locking cotton forceps", "Endo ruler", "Scissors"],
    requiredInputs: ["Master cone", "Shaping length", "Reference point"],
    options: [
      { label: "Cone trimmed and now fits shaping length", nextNodeId: "cone-fit-radiograph", noteEvent: { type: "coneFit.trimmedConeFits" } },
      { label: "Trimmed cone still does not fit", nextNodeId: "cone-short", difficultyFlag: "caution", noteEvent: { type: "coneFit.trimmedConeStillNotFit" } },
      { label: "Cone remains long after trimming", nextNodeId: "cone-long", difficultyFlag: "caution", noteEvent: { type: "coneFit.coneStillLong" } },
    ],
  },
  "cone-fit-radiograph": {
    id: "cone-fit-radiograph",
    phase: "Cone fit",
    title: "Confirm cone fit radiographically",
    chairsideInstruction: "Confirm master cone fit with a periapical radiograph. Record cone fit status before removing the cone and setting it aside for later use.",
    instruments: ["PA radiograph"],
    requiredInputs: ["Cone fit radiograph status"],
    options: [
      { label: "Cone fit radiograph acceptable", nextNodeId: "ready-for-sealer-cone-seating", noteEvent: { type: "coneFit.radiographAcceptable" } },
      { label: "Cone fit radiograph short", nextNodeId: "cone-short", difficultyFlag: "caution", noteEvent: { type: "coneFit.radiographShort" } },
      { label: "Cone fit radiograph long", nextNodeId: "cone-long", difficultyFlag: "caution", noteEvent: { type: "coneFit.radiographLong" } },
    ],
  },
  "ready-for-sealer-cone-seating": {
    id: "ready-for-sealer-cone-seating",
    phase: "Cone fit",
    title: "Ready for sealer / cone seating",
    chairsideInstruction: "Cone fit has been confirmed radiographically. The active canal is ready for the existing sealer and cone seating workflow when the clinician chooses to continue.",
    requiredInputs: ["Cone fit radiograph status", "Master cone", "Shaping length"],
    options: [
      { label: "Proceed to sealer / cone seating workflow", nextNodeId: "dry-for-obturation", noteEvent: { type: "coneFit.readyForSealerConeSeating" } },
    ],
  },
  "dry-for-obturation": {
    id: "dry-for-obturation",
    phase: "Sealer / cone seating",
    title: "Dry canal for obturation",
    chairsideInstruction: "Dry the canal with measured 25/.04 paper points to shaping length. Larger paper points may be used initially, but final drying should be honed with 25/.04 paper points.",
    instruments: ["25/.04 paper points"],
    requiredInputs: ["Shaping length", "Drying status"],
    options: [
      { label: "Paper point dry or slightly damp", nextNodeId: "patency-before-sealer", noteEvent: { type: "drying.readyForSealer" } },
      { label: "Paper point wet", nextNodeId: "dry-for-obturation", difficultyFlag: "caution", noteEvent: { type: "drying.paperPointWet" } },
      { label: "Paper point remains wet after several attempts", nextNodeId: "calcium-hydroxide", difficultyFlag: "high", noteEvent: { type: "drying.persistentWetBeforeObturation" } },
    ],
  },
  "patency-before-sealer": {
    id: "patency-before-sealer",
    phase: "Sealer / cone seating",
    title: "Confirm patency before sealer",
    chairsideInstruction: "Measure 10C hand file to patency length and work at patency length until super loose before sealer placement.",
    instruments: ["10C hand file"],
    requiredInputs: ["Patency length"],
    options: [
      { label: "10C super loose at patency length", nextNodeId: "apply-sealer", noteEvent: { type: "sealer.patencyConfirmed" } },
      { label: "10C does not reach patency length", nextNodeId: "prebend-10c", difficultyFlag: "high", noteEvent: { type: "sealer.patencyNotConfirmed" } },
    ],
  },
  "apply-sealer": {
    id: "apply-sealer",
    phase: "Sealer / cone seating",
    title: "Apply sealer into canal",
    chairsideInstruction: "Place White NaviTip on injectable bioceramic sealer. Measure NaviTip to 15 mm, place passively, and inject while withdrawing coronally. Do not bind the NaviTip. If shaping length is <18 mm, do not advance NaviTip into the last 3 mm of the prepared canal.",
    instruments: ["White NaviTip", "Injectable bioceramic sealer"],
    materials: ["Bioceramic sealer"],
    safetyNotes: ["Do not bind the White NaviTip in the canal.", "For shaping lengths <18 mm, do not advance into the last 3 mm of the prepared canal."],
    options: [
      { label: "Sealer applied with passive NaviTip withdrawal", nextNodeId: "paper-point-through-sealer", noteEvent: { type: "sealer.applied" } },
      { label: "NaviTip binds / cannot place safely", nextNodeId: "calcium-hydroxide", difficultyFlag: "high", noteEvent: { type: "sealer.naviTipUnsafe" } },
    ],
  },
  "paper-point-through-sealer": {
    id: "paper-point-through-sealer",
    phase: "Sealer / cone seating",
    title: "Paper point through sealer",
    chairsideInstruction: "Measure 25/.04 paper point to shaping length and advance through the applied sealer to shaping length.",
    instruments: ["25/.04 paper point"],
    requiredInputs: ["Shaping length"],
    options: [
      { label: "Paper point passed through sealer to shaping length", nextNodeId: "reapply-sealer", noteEvent: { type: "sealer.paperPointDistributed" } },
      { label: "Paper point does not reach shaping length", nextNodeId: "patency-before-sealer", difficultyFlag: "caution", noteEvent: { type: "sealer.paperPointShort" } },
    ],
  },
  "reapply-sealer": {
    id: "reapply-sealer",
    phase: "Sealer / cone seating",
    title: "Re-apply sealer into canal",
    chairsideInstruction: "Re-apply bioceramic sealer with White NaviTip to 15 mm passively while withdrawing coronally. Again, do not bind the NaviTip.",
    instruments: ["White NaviTip", "Injectable bioceramic sealer"],
    materials: ["Bioceramic sealer"],
    safetyNotes: ["Do not bind the White NaviTip in the canal."],
    options: [
      { label: "Sealer re-applied", nextNodeId: "seat-gp-cone", noteEvent: { type: "sealer.reapplied" } },
      { label: "Cannot re-apply sealer safely", nextNodeId: "calcium-hydroxide", difficultyFlag: "high", noteEvent: { type: "sealer.reapplyUnsafe" } },
    ],
  },
  "seat-gp-cone": {
    id: "seat-gp-cone",
    phase: "Sealer / cone seating",
    title: "Seat pre-fit GP cone",
    chairsideInstruction: "Advance the pre-fit .04 tapered gutta-percha cone into the canal to shaping length.",
    instruments: ["Pre-fit .04 tapered GP cone"],
    requiredInputs: ["Master cone", "Shaping length"],
    options: [
      { label: "GP cone seats at shaping length", nextNodeId: "evaluate-orifice-gap", noteEvent: { type: "gpSeating.coneSeated" } },
      { label: "GP cone does not seat to shaping length", nextNodeId: "patency-before-sealer", difficultyFlag: "caution", noteEvent: { type: "gpSeating.coneShortAfterSealer" } },
      { label: "GP cone advances beyond shaping length", nextNodeId: "gauge-obturation-30", difficultyFlag: "high", noteEvent: { type: "gpSeating.coneLongAfterSealer" } },
    ],
  },
  "evaluate-orifice-gap": {
    id: "evaluate-orifice-gap",
    phase: "Downpack / backfill",
    title: "Evaluate orifice gap space",
    chairsideInstruction: "Evaluate visible orifice gap space after GP cone seating. Decide whether the orifice is round, ovoid, or has no visible gap.",
    options: [
      { label: "No visible gap space", nextNodeId: "sear-gp-cones", noteEvent: { type: "downpack.noGapSpace" } },
      { label: "Gap space in round orifice", nextNodeId: "modified-downpack", noteEvent: { type: "downpack.roundGapSpace" } },
      { label: "Gap space in ovoid orifice", nextNodeId: "add-accessory-cones", noteEvent: { type: "downpack.ovoidGapSpace" } },
    ],
  },
  "modified-downpack": {
    id: "modified-downpack",
    phase: "Downpack / backfill",
    title: "Modified GP downpack",
    chairsideInstruction: "Measure heat plugger to 15 mm. Activate heat source and advance to the reference level. Deactivate for 5 seconds, then reactivate and remove plugger.",
    instruments: ["Electric heat source", "Heat plugger"],
    safetyNotes: ["Consider radiograph if cone movement or placement is uncertain."],
    options: [
      { label: "Coronal GP removed and apical GP stayed in place", nextNodeId: "reapply-sealer-on-gp", noteEvent: { type: "downpack.modifiedSuccessful" } },
      { label: "Little or no GP removed", nextNodeId: "modified-downpack", difficultyFlag: "caution", noteEvent: { type: "downpack.littleGpRemoved" } },
      { label: "Cone moved or was removed", nextNodeId: "fit-master-cone", difficultyFlag: "high", noteEvent: { type: "downpack.coneMoved" } },
    ],
  },
  "add-accessory-cones": {
    id: "add-accessory-cones",
    phase: "Downpack / backfill",
    title: "Add accessory GP cones",
    chairsideInstruction: "Place additional 25/.04 GP cones into visible gap spaces as needed until no visible gap remains.",
    instruments: ["25/.04 GP cones"],
    options: [
      { label: "Accessory cones added; no visible gap remains", nextNodeId: "sear-gp-cones", noteEvent: { type: "downpack.accessoryConesAdded" } },
      { label: "Cannot fill gap predictably", nextNodeId: "modified-downpack", difficultyFlag: "caution", noteEvent: { type: "downpack.accessoryConeDifficulty" } },
    ],
  },
  "sear-gp-cones": {
    id: "sear-gp-cones",
    phase: "Downpack / backfill",
    title: "Sear GP cones",
    chairsideInstruction: "Use electric heat source and heat plugger to heat-sear GP cone(s) at and above the canal orifice.",
    instruments: ["Electric heat source", "Heat plugger"],
    options: [{ label: "GP cone(s) seared at orifice", nextNodeId: "vertical-compaction", noteEvent: { type: "downpack.gpSeared" } }],
  },
  "vertical-compaction": {
    id: "vertical-compaction",
    phase: "Downpack / backfill",
    title: "Light vertical compaction",
    chairsideInstruction: "Use an endodontic plugger to apply light vertical compaction force on remaining GP in the canal.",
    instruments: ["Endodontic plugger"],
    options: [
      { label: "GP maintained position", nextNodeId: "canal-obturation-complete", noteEvent: { type: "downpack.gpStableAfterCompaction" } },
      { label: "GP moved apically", nextNodeId: "reapply-sealer-on-gp", difficultyFlag: "caution", noteEvent: { type: "downpack.gpMovedApically" } },
    ],
  },
  "reapply-sealer-on-gp": {
    id: "reapply-sealer-on-gp",
    phase: "Downpack / backfill",
    title: "Re-apply sealer over visible GP",
    chairsideInstruction: "Place a small amount of bioceramic sealer on top of the visible GP before backfill.",
    materials: ["Bioceramic sealer"],
    options: [{ label: "Sealer applied over visible GP", nextNodeId: "backfill-canal", noteEvent: { type: "backfill.sealerOnGp" } }],
  },
  "backfill-canal": {
    id: "backfill-canal",
    phase: "Downpack / backfill",
    title: "Backfill remaining canal space",
    chairsideInstruction: "Allow thermoplastic GP delivery system to reach full temperature. Seat tip on remaining GP for 5 seconds, inject thermoplastic GP, and allow passive withdrawal.",
    instruments: ["Thermoplastic GP delivery system"],
    materials: ["Thermoplastic GP"],
    options: [
      { label: "Backfill completed", nextNodeId: "compact-backfill", noteEvent: { type: "backfill.completed" } },
      { label: "Backfill not predictable", nextNodeId: "reapply-sealer-on-gp", difficultyFlag: "caution", noteEvent: { type: "backfill.difficulty" } },
    ],
  },
  "compact-backfill": {
    id: "compact-backfill",
    phase: "Downpack / backfill",
    title: "Compact injected GP",
    chairsideInstruction: "Apply light vertical compaction force on injected GP. If plugger pokes holes, increase plugger size and repeat backfill if needed.",
    instruments: ["Endodontic plugger"],
    options: [
      { label: "GP remains at canal orifice", nextNodeId: "canal-obturation-complete", noteEvent: { type: "backfill.compactedStable" } },
      { label: "GP moves apically", nextNodeId: "reapply-sealer-on-gp", difficultyFlag: "caution", noteEvent: { type: "backfill.gpMovedApically" } },
      { label: "Excess GP extends into chamber", nextNodeId: "canal-obturation-complete", noteEvent: { type: "backfill.excessInChamber" } },
      { label: "Plugger pokes holes", nextNodeId: "backfill-canal", difficultyFlag: "caution", noteEvent: { type: "backfill.pluggerHoles" } },
    ],
  },
  "canal-obturation-complete": {
    id: "canal-obturation-complete",
    phase: "Downpack / backfill",
    title: "Active canal obturation complete",
    chairsideInstruction: "The active canal has been obturated/backfilled. If other canals still require treatment, continue another canal before final chamber cleanup and restoration. Proceed to chamber cleanup only when all canals are ready.",
    options: [
      { label: "All canals obturated; proceed to chamber cleanup", nextNodeId: "cleanup-chamber", noteEvent: { type: "workflow.allCanalsReadyForClosure" } },
    ],
  },
  "cleanup-chamber": {
    id: "cleanup-chamber",
    phase: "Closure",
    title: "Clean pulp chamber",
    chairsideInstruction: "Remove residual GP from the pulp chamber with a small spoon excavator and electric heat source as needed.",
    instruments: ["Small spoon excavator", "Electric heat source"],
    options: [{ label: "Residual GP removed from chamber", nextNodeId: "rinse-chamber", noteEvent: { type: "closure.chamberGpRemoved" } }],
  },
  "rinse-chamber": {
    id: "rinse-chamber",
    phase: "Closure",
    title: "Rinse pulp chamber",
    chairsideInstruction: "Rinse the pulp chamber with water until residual sealer is removed.",
    materials: ["Water rinse"],
    options: [{ label: "Chamber rinsed clean", nextNodeId: "close-access", noteEvent: { type: "closure.chamberRinsed" } }],
  },
  "close-access": {
    id: "close-access",
    phase: "Closure",
    title: "Close access",
    chairsideInstruction: "Close the access using the selected closure method.",
    materials: ["Sponge", "Temporary restorative material", "Orifice barrier", "Final restorative material"],
    options: [
      { label: "Sponge and temporary restoration placed", nextNodeId: "endodontic-pathway-complete", noteEvent: { type: "closure.temporary" } },
      { label: "Orifice barrier and temporary restoration placed", nextNodeId: "endodontic-pathway-complete", noteEvent: { type: "closure.orificeBarrierTemporary" } },
      { label: "Final restoration placed", nextNodeId: "endodontic-pathway-complete", noteEvent: { type: "closure.finalRestoration" } },
    ],
  },
  "persistent-wet": {
    id: "persistent-wet",
    phase: "Troubleshooting",
    title: "Persistent wet canal",
    chairsideInstruction: "Repeat drying with measured paper points. If still wet, place calcium hydroxide and temporize.",
    instruments: ["25/.04 paper points", "White NaviTip"],
    materials: ["Calcium hydroxide", "Temporary restorative material"],
    options: [
      { label: "Canal dried", nextNodeId: "attach-eal", noteEvent: { type: "drying.canalDriedAfterRepeat" } },
      { label: "Persistent wet canal · place calcium hydroxide", nextNodeId: "calcium-hydroxide", difficultyFlag: "high", noteEvent: { type: "drying.persistentWetConfirmed" } },
    ],
  },
  "calcium-hydroxide": {
    id: "calcium-hydroxide",
    phase: "Medication / temporisation",
    title: "Place calcium hydroxide",
    chairsideInstruction: "Place calcium hydroxide with White NaviTip. Proceed to temporary closure.",
    instruments: ["White NaviTip"],
    materials: ["Calcium hydroxide"],
    options: [{ label: "Calcium hydroxide placed", nextNodeId: "temporary-closure", noteEvent: { type: "medication.calciumHydroxidePlaced" } }],
  },
  "temporary-closure": {
    id: "temporary-closure",
    phase: "Medication / temporisation",
    title: "Temporary closure",
    chairsideInstruction: "Close access with sponge and temporary restorative material.",
    materials: ["Sponge", "Temporary restorative material"],
    options: [{ label: "Access temporized", nextNodeId: "endodontic-pathway-complete", noteEvent: { type: "closure.temporary" } }],
  },
  "refer-pathway": {
    id: "refer-pathway",
    phase: "Medication / temporisation",
    title: "Referral / stop pathway",
    chairsideInstruction: "Document difficulty and consider medication/temporization or referral.",
    safetyNotes: ["Referral is appropriate when treatment exceeds comfort, skill, equipment, or case difficulty limits."],
    options: [
      { label: "Document referral recommended", nextNodeId: "endodontic-pathway-complete", difficultyFlag: "refer", noteEvent: { type: "treatment.referralRecommended" } },
      { label: "Medicate and temporize instead", nextNodeId: "calcium-hydroxide", difficultyFlag: "refer", noteEvent: { type: "treatment.medicateTemporizeSelected" } },
    ],
  },
  "endodontic-pathway-complete": {
    id: "endodontic-pathway-complete",
    phase: "Export",
    title: "Pathway complete",
    chairsideInstruction: "This pathway has enough structured data to generate note outputs. Continue another canal, undo, or copy the note.",
    options: [
      { label: "Return to pre-op", nextNodeId: "preop", noteEvent: { type: "workflow.returnedToStart" } },
    ],
  },
};

export const handoffNodeIds = new Set([
  "ready-for-obturation",
  "ready-for-sealer-cone-seating",
  "canal-obturation-complete",
  "endodontic-pathway-complete",
]);
