import fs from "node:fs";
import path from "node:path";
import { protocolNodes } from "../src/nodedent/protocol/nodes";
import { phases } from "../src/nodedent/protocol/phases";

type ProtocolGraphNode = {
  id: string;
  mermaidId: string;
  phase: string;
  title: string;
};

type ProtocolGraphEdge = {
  from: string;
  to: string;
  label: string;
  difficultyFlag: string;
  noteEventType: string;
  isSelfLoop: boolean;
};

const outDir = path.resolve("docs/generated");
const mermaidPath = path.join(outDir, "endo-workflow.mmd");
const markdownPath = path.join(outDir, "endo-workflow.md");

function escapeMermaidText(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\|/g, "&#124;")
    .replace(/\r?\n/g, "<br/>");
}

function makeMermaidId(id: string) {
  return `node_${id.replace(/[^A-Za-z0-9]/g, "_")}`;
}

function buildGraph() {
  const ids = new Set(Object.keys(protocolNodes));
  const nodes: ProtocolGraphNode[] = Object.values(protocolNodes).map((node) => ({
    id: node.id,
    mermaidId: makeMermaidId(node.id),
    phase: node.phase,
    title: node.title,
  }));
  const sanitizedIds = new Map<string, string>();
  const errors: string[] = [];

  nodes.forEach((node) => {
    if (!ids.has(node.id)) errors.push(`Node ${node.id} is not keyed by its own id in protocolNodes.`);
    const existing = sanitizedIds.get(node.mermaidId);
    if (existing && existing !== node.id) errors.push(`Mermaid id collision: ${existing} and ${node.id} both map to ${node.mermaidId}.`);
    sanitizedIds.set(node.mermaidId, node.id);
  });

  const edges: ProtocolGraphEdge[] = Object.values(protocolNodes).flatMap((node) =>
    node.options.map((option) => {
      if (!ids.has(option.nextNodeId)) errors.push(`${node.id} option "${option.label}" points to missing node ${option.nextNodeId}.`);
      return {
        from: node.id,
        to: option.nextNodeId,
        label: option.label,
        difficultyFlag: option.difficultyFlag || "",
        noteEventType: option.noteEvent?.type || "",
        isSelfLoop: node.id === option.nextNodeId,
      };
    })
  );

  if (errors.length) {
    throw new Error(`Cannot export workflow graph:\n- ${errors.join("\n- ")}`);
  }

  return { nodes, edges };
}

function edgeLabel(edge: ProtocolGraphEdge) {
  const parts = [edge.label];
  if (edge.isSelfLoop) parts.push("loop");
  if (edge.difficultyFlag) parts.push(`difficulty: ${edge.difficultyFlag}`);
  if (edge.noteEventType) parts.push(`event: ${edge.noteEventType}`);
  return escapeMermaidText(parts.join(" | "));
}

function nodeLabel(node: ProtocolGraphNode) {
  return `${escapeMermaidText(node.title)}<br/><small>${escapeMermaidText(node.id)}</small>`;
}

function renderMermaid(nodes: ProtocolGraphNode[], edges: ProtocolGraphEdge[]) {
  const nodeById = new Map(nodes.map((node) => [node.id, node]));
  const phaseSet = new Set(nodes.map((node) => node.phase));
  const orderedPhases = [...phases.filter((phase) => phaseSet.has(phase)), ...[...phaseSet].filter((phase) => !phases.includes(phase)).sort()];
  const lines = [
    "%% Generated by scripts/export-protocol-graph.ts from src/nodedent/protocol/nodes.ts",
    "flowchart TD",
    "  classDef default fill:#ffffff,stroke:#d8e0ec,color:#0f1f3d;",
    "  classDef caution fill:#fff7e6,stroke:#d99a2b,color:#4a3200;",
    "  classDef high fill:#ffecec,stroke:#d15252,color:#5b0000;",
    "  classDef refer fill:#f5e8ff,stroke:#8651c8,color:#2d0b52;",
  ];

  orderedPhases.forEach((phase) => {
    const phaseNodes = nodes.filter((node) => node.phase === phase);
    lines.push(`  subgraph phase_${makeMermaidId(phase)}["${escapeMermaidText(phase)}"]`);
    phaseNodes.forEach((node) => {
      lines.push(`    ${node.mermaidId}["${nodeLabel(node)}"]`);
    });
    lines.push("  end");
  });

  edges.forEach((edge, index) => {
    const from = nodeById.get(edge.from);
    const to = nodeById.get(edge.to);
    if (!from || !to) return;
    lines.push(`  ${from.mermaidId} -->|"${edgeLabel(edge)}"| ${to.mermaidId}`);
    if (edge.difficultyFlag) lines.push(`  linkStyle ${index} stroke:${edge.difficultyFlag === "refer" ? "#8651c8" : edge.difficultyFlag === "high" ? "#d15252" : "#d99a2b"},stroke-width:2px;`);
  });

  return `${lines.join("\n")}\n`;
}

function renderMarkdown(mermaid: string, nodes: ProtocolGraphNode[], edges: ProtocolGraphEdge[]) {
  const selfLoops = edges.filter((edge) => edge.isSelfLoop);
  const difficultyEdges = edges.filter((edge) => edge.difficultyFlag);

  return `# Endodontic Workflow Graph

Generated from \`src/nodedent/protocol/nodes.ts\` by \`npm run docs:workflow-graph\`.

## Summary

- Nodes: ${nodes.length}
- Edges: ${edges.length}
- Self-loops: ${selfLoops.length}
- Difficulty edges: ${difficultyEdges.length}
- Phases: ${new Set(nodes.map((node) => node.phase)).size}

## Reading The Graph

- Each node shows the chairside card title and protocol node id.
- Edge labels show the decision option, self-loop marker, difficulty flag, and note event type when present.
- Caution, high, and referral branches use distinct edge colors in Mermaid renderers.
- The standalone Mermaid source is [endo-workflow.mmd](endo-workflow.mmd).

## Mermaid

\`\`\`mermaid
${mermaid.trim()}
\`\`\`
`;
}

function writeFile(filePath: string, content: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
}

const { nodes, edges } = buildGraph();
const mermaid = renderMermaid(nodes, edges);
writeFile(mermaidPath, mermaid);
writeFile(markdownPath, renderMarkdown(mermaid, nodes, edges));

console.log(`Wrote ${path.relative(process.cwd(), mermaidPath)} and ${path.relative(process.cwd(), markdownPath)}.`);
